### PR TITLE
added script for gesture webcam demo

### PR DESCRIPTION
**Pull request by dineshp**
added script for real-time gesture recognition webcam demo (https://www.youtube.com/watch?v=6PAvFzV4Yfo)

### CODE REVIEW

**Comment by 595448755** [comment]
[root@01:/ai/trn-pytorch# python fps_dem_trn.py
[INFO] sampling THREADED frames from webcam...
VIDEOIO ERROR: V4L: can't open camera by index 0
Multi-Scale Temporal Relation Network Module in use ['8-frame relation', '7-frame relation', '6-frame relation', '5-frame relation', '4-frame relation', '3-frame relation', '2-frame relation']
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "fps_dem_trn.py", line 140, in <module>
    crop_img = frame[0:720, 0:720]
TypeError: 'NoneType' object is not subscriptable
terminate called without an active exception
Aborted (core dumped)

I got an error while running this command: " python fps_dem_trn.py ".   Ask how to solve it ,please.
Many thanks.

**Comment by 595448755** [comment]
@dineshp  Can you help me.
What can I do next?
Thanks.

**Comment by dineshp** [comment]
https://answers.opencv.org/question/199105/videoio-error-v4l-cant-open-camera-by-index-0/

**Comment by dineshp** [comment]
https://github.com/skvark/opencv-python/issues/124

**Comment by 595448755** [comment]
@dineshp  Thanks very much.
I got an error when I run the command "sudo modprobe bcm2835-v4l2".
root@01:/ai/trn-pytorch# root@ai-k4-u18-c92n742-01:/ai/trn-pytorch# sudo modprobe bcm2835-v4l2
-bash: root@01:/ai/trn-pytorch#: No such file or directory
cm2835-v4l2 not found in directory /lib/modules/4.15.0-49-genericroot@ai-k4-u18-c92n742-01:/ai/trn-pytorch# modprobe: FATAL: Module bcm2835-v4l2 not found in directory /lib/modules/4.15.0-49-generic

I have no "raspberry pi",
I use the laptop remote(SSH) call Ubuntu18.04 server, how to use the laptop camera connection to  webcam.

**Comment by dineshp** [comment]
> @dineshp Thanks very much.
> I got an error when I run the command "sudo modprobe bcm2835-v4l2".
> root@01:/ai/trn-pytorch# root@ai-k4-u18-c92n742-01:/ai/trn-pytorch# sudo modprobe bcm2835-v4l2
> -bash: root@01:/ai/trn-pytorch#: No such file or directory
> cm2835-v4l2 not found in directory /lib/modules/4.15.0-49-genericroot@ai-k4-u18-c92n742-01:/ai/trn-pytorch# modprobe: FATAL: Module bcm2835-v4l2 not found in directory /lib/modules/4.15.0-49-generic
> 
> I have no "raspberry pi",
> I use the laptop remote(SSH) call Ubuntu18.04 server, how to use the laptop camera connection to webcam.

If you don't have a webcam you can interact with you are out of luck

**Comment by 595448755** [comment]
@dineshp   
Thanks for sharing!

**Comment by ddb4ng** [comment]
> [root@01:/ai/trn-pytorch# python fps_dem_trn.py
> [INFO] sampling THREADED frames from webcam...
> VIDEOIO ERROR: V4L: can't open camera by index 0
> Multi-Scale Temporal Relation Network Module in use ['8-frame relation', '7-frame relation', '6-frame relation', '5-frame relation', '4-frame relation', '3-frame relation', '2-frame relation']
> Freezing BatchNorm2D except the first one.
> Traceback (most recent call last):
> File "fps_dem_trn.py", line 140, in 
> crop_img = frame[0:720, 0:720]
> TypeError: 'NoneType' object is not subscriptable
> terminate called without an active exception
> Aborted (core dumped)
> 
> I got an error while running this command: " python fps_dem_trn.py ". Ask how to solve it ,please.
> Many thanks.

Did you manage to solve this issue? We would like to know how

**Comment by metalbubble** [comment]
Thanks @dineshp !

**Pull request merged**
